### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by JayseeXD** [OpenFactorioServerManager/factorio-server-manager#180] opened 2020-08-23 10:43 UTC
Hi guys,

Probably me doing something wrong however, launching the factorio-server-manager via cmd prompt gets me the following : 
2020/08/23 11:32:08 Loaded Factorio settings from C:\Factorio\config\server-settings.json
2020/08/23 11:32:08 error on loading factorio version: exec: "C:\\Factorio\\bin\\x64\\factorio": file does not exist
2020/08/23 11:32:08 Error occurred during FactorioServer initializaion: exec: "C:\\Factorio\\bin\\x64\\factorio": file does not exist

I'm using the following to launch... Again sorry if i'm messing this up:
cd C:\Factorio\factorio-server-manager
.\factorio-server-manager --dir C:\Factorio\

**Comment by Jaysee-DRP** [comment] 2020-08-29 08:37
It's the server files downloaded from the factorio website. the factorio file exists in that folder too.

**Comment by knoxfighter** [comment] 2020-08-30 02:12
ok, i tried out multiple things, and the only variant i can find, where this error occurs, is, when the wrong factorio version is downloaded.
So make sure, that you download the windows version of factorio and not a linux/mac version. Unluckily it has no headless server for windows, so you need to download the full version to run it correctly.

If it helps to download the windows version, try it again, and write us, if the error still persists :)

**Comment by jannaahs** [comment] 2021-06-26 23:08
I am closing this issue, because the bug could not be reproduced and no additional information was provided. Therefore I assume it's fixed. If there is any new information, we can reopen this issue.

**Closed by jannaahs** 2021-06-26 23:08 UTC
Labels: Information needed, bug
