### ISSUE TITLE
rcon port does not randomize

### ISSUE THREAD

**Issue by jhnguyen521** [OpenFactorioServerManager/factorio-server-manager#142] opened 2019-03-12 17:21 UTC
Rcon port does not randomize and no option to manually change it

**Comment by Psychomantis71** [comment] 2019-07-29 13:27
@justindude521 can you please provide some logs and your config for us to look into this?
(please depersonalise all the logs and config files before uploading)

**Comment by Katharsas** [comment] 2020-11-22 03:38
Hi, 
i have the same problem on Ubuntu Focal. Its really easy to reproduce. Just have two copies of factorio-server-manager and Factorio and start both of them (on different ports, like 34197 and 34198):
``` 
   0.000 2020-11-22 04:06:08; Factorio 1.0.0 (build 54889, linux64, headless)
   0.050 Operating system: Linux (Ubuntu 20.04)
   0.050 Program arguments: "../factorio_1.0.0/bin/x64/factorio" "--bind" "0.0.0.0" "--port" "34198" "--server-settings" "../factorio_1.0.0/config/server-settings.json" "--rcon-port" "43081" "--rcon-password" <private> "--server-adminlist" "../factorio_1.0.0/config/server-adminlist.json" "--start-server" "../factorio_1.0.0/saves/<private>.zip"
```

This bug makes it impossile to run two Factorio servers at the same time with two separate managers, because the rcon port is always blocked.

**Comment by knoxfighter** [comment] 2020-12-09 17:13
Fixed in develop branch. Will be inside next release.

**Closed by knoxfighter** 2020-12-09 17:13 UTC
Labels: bug
