### ISSUE TITLE
Trying to install mods fails during a request with "?page_size=max"

### ISSUE THREAD

**Issue by EinPinsel** [OpenFactorioServerManager/factorio-server-manager#226] opened 2021-01-18 22:02 UTC
Thanks for this awesome little tool. I like it a lot :) Currently I'm trying to install mods into a brand new server and currently it fails because requesting all the mods ends up in an error. Currently there are only about 320 pages of mods, so I could hotfix it, but I'm not sure if that would worth a PR
https://github.com/OpenFactorioServerManager/factorio-server-manager/blob/bcbf3ffd3d15dd6600f25ae6681d1bf6f55a9374/src/factorio/mod_portal.go#L33

**Comment by mroote** [comment] 2021-01-18 22:06
Hi @EinPinsel,

Glad you like the manager! @knoxfighter just pushed a fix for this issue to develop yesterday.

**Comment by EinPinsel** [comment] 2021-01-18 22:11
Ups. Now I did it myself as well 😅 I tried to help :D

**Comment by mroote** [comment] 2021-01-18 22:12
haha thanks for the contribution! You can pull the develop docker container in the meantime to get the fixed version.

**Comment by knoxfighter** [comment] 2021-01-18 22:13
Duplicate of #219

**Closed by knoxfighter** 2021-01-18 22:13 UTC
Labels: duplicate
